####################################################################################
#
# Generated by eda_pt_script.tcl	#1
#              eda_pt_conversion.tcl	#1
#              in d:/altera/90/quartus/common/tcl/internal/eda_pt/.
#
# Quartus:  Version 9.0 Build 132 02/25/2009 SJ Full Version
#
# Project:  PipelineUniProcessor
# Revision: PipelineUniProcessor
#
# Date: Mon Nov 23 4:08:37 PM China Standard Time 2009
#
####################################################################################


set _col0 [ get_ports {CLK}]



